server:
  port: 8080

spring:
  mvc:
    view:
      prefix: classpath:templates/views
      suffix: .html
  thymeleaf:
    prefix: classpath:templates
    suffix: .html
    cache: false
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: foo
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: test1234
#      cluster:
#        nodes:
#          127.0.0.1:6380,
#          127.0.0.1:6381,
#          127.0.0.1:6382
#        max-redirects: 5
#      lettuce:
#        pool:
#          enabled: true
#          max-active: 8
#          max-wait: 1000
#          max-idle: 500

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    master:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://127.0.0.1:13306/prime?useUnicode=true&characterEncoding=utf8
      username: root
      password: root
    slave:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://127.0.0.1:23306/prime?readOnly=true&useUnicode=true&characterEncoding=utf8
      username: root
      password: root


#logging:
#  config: ${conf.logging}/BAKC_logback-spring

logging:
  level:
    org:
      hibernate:
        type: trace
      springframework:
        #transaction: DEBUG
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

