SET foreign_key_checks = 0;
DROP TABLE IF EXISTS `TB_COMPANY`;
CREATE TABLE `TB_COMPANY` (
`IDX`	BIGINT(8)	NOT NULL AUTO_INCREMENT,
`COM_NAME`	VARCHAR(30)	NOT NULL,
`COM_UUID`	BINARY(16)	NOT NULL,
`COM_PHONE`	VARCHAR(30)	NULL,
`COM_EMAIL`	VARCHAR(50)	NULL,
`COM_ADDRESS`	VARCHAR(300)	NULL,
`COM_ADDRESS_DETAIL`	VARCHAR(300)	NULL,
`IS_DELETE`	BOOLEAN	NULL DEFAULT 0,
`IS_USE`	BOOLEAN	NULL DEFAULT 1,
`REG_DATE`	DATETIME	NULL DEFAULT NOW(),
`MOD_DATE`	DATETIME	NULL,
PRIMARY KEY (`IDX`)
);

DROP TABLE IF EXISTS `TB_USER`;
CREATE TABLE `TB_USER` (
`IDX`	BIGINT(8)	NOT NULL AUTO_INCREMENT,
`COMPANY_IDX`	BIGINT(8)	NOT NULL,
`USER_ID`	VARCHAR(30)	NOT NULL,
`USER_PASSWORD`	VARCHAR(300)	NOT NULL,
`USER_NAME`	VARCHAR(30)	NOT NULL,
`USER_EMAIL`	VARCHAR(50)	NOT NULL,
`USER_PHONE`	VARCHAR(30)	NOT NULL,
`USER_ADDRESS`	VARCHAR(300)	NOT NULL,
`USER_ADDRESS_DETAIL`	varchar(300)	NULL,
`AUTHORITY`	VARCHAR(30)	NOT NULL,
`IS_DELETE`	BOOLEAN	NULL DEFAULT 0,
`IS_USE`	BOOLEAN	NULL DEFAULT 1,
`REG_DATE`	DATETIME	NULL DEFAULT NOW(),
`MOD_DATE`	DATETIME	NULL,
PRIMARY KEY (`IDX`),
FOREIGN KEY (COMPANY_IDX) REFERENCES TB_COMPANY(IDX)
);
SET foreign_key_checks = 1;